# Pandas and Numpy: 1 Dimensional Data
Numpy stands for Numerical Python.

Both, Pandas and Numpy have data structures used to represent one dimensional data. In Pandas this is called a `Series`, whereas in Numpy this is an `Array`. Pandas `Series` are built on top of Numpy `Arrays` and have more features than the Numpy `Arrays`, however the Numpy `Array` is simpler.

## Numpy Array
A Numpy Array is similar to a python list, in that it contains a sequence of elements. The following are the similarities and differences

#### Similarities
 * Elements are accessed by position (indexed at 0) eg. numarr[0]
 * Range of elements accessible using slicing. eg. numarr[2:5]
 * Loops can be used to access elements. eg. for elem in numarr:

#### Differences
 * Numpy arrays are *designed* for each element to have the same data type. They can be different but its not recommended you do so
 * The arrays offer a set of convenient functions eg. numarr.mean(), numarr.std()
 * Can be multi-dimensional: Similar to making a built-in list of lists.
 * Support for vector operations

In [19]:
#%matplotlib inline

import pandas as pd
import numpy as np

In [20]:
# Change False to True for each block of code to see what it does
countries = np.array([
    'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
    'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
    'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
    'Belize', 'Benin', 'Bhutan', 'Bolivia',
    'Bosnia and Herzegovina'
])

employment = np.array([
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076
])

# Accessing elements
if False:
    print(countries[0])
    print(countries[-2])

# Slicing
if False:
    print(countries[0:3])
#    print(countries[:3])
#     print(countries[17:])
    print(countries[-3:])
    print(countries[:])
    print(countries[::-1])

# Element types
if False:
    print(countries.dtype)
    print(employment.dtype)
    print(np.array([0, 1, 2, 3]).dtype)
    print(np.array([1.0, 1.5, 2.0, 2.5]).dtype)
    print(np.array([True, False, True]).dtype)
    print(np.array(['AL', 'AK', 'AZ', 'AR', 'CA']).dtype)

# Looping
if False:
    for emp in employment:
        print('Examining employment {}'.format(emp))


# Numpy functions
if True:
    print(employment.mean())
    print(employment.std())
    print(employment.max())
    print(employment.sum())
    print(employment.argmax())
    
#     print(np.random.randn(10))

58.6850000385
9.33826911369
75.69999695
1173.70000077
3


#### Exercise 

Try to find the maximum employment value in the list of employment values and the corresponding country that has that maximum employment value

In [21]:
# First 20 countries with employment data
countries = np.array([
    'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
    'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
    'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
    'Belize', 'Benin', 'Bhutan', 'Bolivia',
    'Bosnia and Herzegovina'
])

# Employment data in 2007 for those 20 countries
employment = np.array([
    55.70000076,  51.40000153,  50.5       ,  75.69999695,
    58.40000153,  40.09999847,  61.5       ,  57.09999847,
    60.90000153,  66.59999847,  60.40000153,  68.09999847,
    66.90000153,  53.40000153,  48.59999847,  56.79999924,
    71.59999847,  58.40000153,  70.40000153,  41.20000076
])


def max_employment(countries, employment):
    """
    Fill in this function to return the name of the country
    with the highest employment in the given employment
    data, and the employment in that country.
    
    Hint: Look up np.argmax()
    """
    return countries[employment.argmax()], employment.max()

print(max_employment(countries, employment))

('Angola', 75.699996949999999)


### Vector operations
Numpy arrays come with support for various vector operations. This where the arrays are worked up as matrices in the linear algebra model.

 * Math operations: +, -, *, /
 * Logical operations: |, &, ~ (Not)
 * Comparison operations: >, <, ==, !=

In [22]:
lista = [1, 2, 3]
listb = [4, 5, 6]

print("Python builtin lists")
print(lista + listb)

a = np.array(lista)
b = np.array(listb) 

print("\nNumpy Arrays")
print(a + b)
print(a * b)
print(a > b)

c = 10
print(a - c)

logica = np.array([True, False, True])
logicb = np.array([False, False, False])

print(logica | logicb)

Python builtin lists
[1, 2, 3, 4, 5, 6]

Numpy Arrays
[5 7 9]
[ 4 10 18]
[False False False]
[-9 -8 -7]
[ True False  True]


#### Exercise
For the employment array provided above, calculate another array that lists out the deviation of each from the mean in multiples of standard deviations. So if a data set has a mean of 10 and a standard deviation of 2, then a value of 12 is 1 standard deviation away from the mean (12 - 10)/2

In [23]:
def standardize_data(employment):
    """
    Standardize it to have each element in the array contain the multiple of standard deviations away
    from the mean
    :param employment: 
    :return: 
    """
    # For each element, calculate its difference from the mean and divide by the standard deviation
    # to determine how many std_devs away from the mean the value is.
    
    return (employment - employment.mean()) / employment.std()

std_emp = standardize_data(employment)
print(std_emp)

[-0.31965231 -0.780123   -0.87650077  1.82207181 -0.03051941 -1.99019768
  0.30144772 -0.16973184  0.23719615  0.84758731  0.18365304  1.00821665
  0.87971351 -0.56595055 -1.07996476 -0.20185762  1.38301845 -0.03051941
  1.2545153  -1.87240259]


### In Place
Note that certain operators in Numpy result in operations performed in place, rather than on copies or new values of the array.

#### + vs +=
Consider this snippet

In [24]:
a = np.array([1, 2, 3, 4, 5])
b = a

a += 2  # a = a + 2
print(a)
print(b)

[3 4 5 6 7]
[3 4 5 6 7]


Here the += operator modifies the existing array in place, i.e. it does not create a new array and shift a's reference to it. Instead, with both a and b pointing to the same array, the += modifies the array in place, which is why b also sees the updated values.

This is different from how + works, which, as one would expect, creates a new array and shifts the pointer reference

In [25]:
a = np.array([3, 6, 9])
b = a
a = a + 3
print(b)
print(a)

[3 6 9]
[ 6  9 12]


#### Slicing
Slicing in numpy arrays works differently than on python lists. A slice of a numpy array creates a `view` into the same array based on the bounds of the slice. Thus modifications to the view (or slice) will result in modifications to the original array

In [26]:
print("Numpy")
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
b = a[:3]
b[0] = 300
print(a)
print(b)

a[2] = 34
print(a)
print(b)

# Python built-in lists
print("Python lists")
a = [1,2,3,4,5,6]
b = a[:3]
a[2] = 300

print(a)
print(b)

Numpy
[300   2   3   4   5   6   7   8   9]
[300   2   3]
[300   2  34   4   5   6   7   8   9]
[300   2  34]
Python lists
[1, 2, 300, 4, 5, 6]
[1, 2, 3]


### Index Arrays
Numpy Arrays can be used as indexes into other Numpy arrays to return a filtered list of elements. You would start with a numpy array, and then combine it with an array of booleans which would just return the elements from the first array for which the booleans were true

In [27]:
a = np.array([1, 2, 3])
b = np.array([True, False, True])

# print(a[b])

print(a)
# print(a[b])

[1 2 3]


This could be further concised down and used as a filter. eg. To print out the elements of a that are greater than 2, you would use index arrays like so

In [28]:
# a > 2 returns an array of booleans
print(a > 2)
print(a[a >= 2])

[False False  True]
[2 3]


Here (a > 2) creates an index array of booleans [False, False, True], which when used as an index into a, will return just the elements of a for which the index is True

In [29]:
# Using index arrays
if False:
    a = np.array([1, 2, 3, 4])
    b = np.array([True, True, False, False])
    
    print(a[b])
    print(a[np.array([True, False, True, False])])
    
# Creating the index array using vectorized operations
if False:
    a = np.array([1, -12, -3, 2, 1])
    b = (a > 0)

    print(a)
    print(b)
    print(a[b])
    print(a[a >= 2])
    
# Creating the index array using vectorized operations on another array
if True:
    a = np.array([1, 2, 3, 4, 5])
    b = np.array([1, 2, 3, 2, 1])
    
#     print(b == 2)
    print(b[b == 2])

[2 2]


#### Exercise

For the standardised employment array, print out the employment value for a given country. 

To do this you should create an index from the countries array for the country that you need and index that into the std_emp array. You can assume for this exercise that the country and employment arrays are the same length with corresponding array indexes.

In [30]:
country = "Angola"   #answer below
print(employment[countries == country])
print(countries[employment > 53])

[ 75.69999695]
['Afghanistan' 'Angola' 'Argentina' 'Australia' 'Austria' 'Azerbaijan'
 'Bahamas' 'Bahrain' 'Bangladesh' 'Barbados' 'Belarus' 'Belize' 'Benin'
 'Bhutan' 'Bolivia']


## Pandas Series

A Series is a data structure from the Pandas data library that is used for one-dimensional data. It supports for all operations found on numpy arrays (indexes access, looping, vector operations, etc.) but also provides added functionality. 

### Pandas Series Indexes

It is useful to think of Pandas Series a cross between a Dictionary and a List. In a Series, as in Numpy Array, elements can be accessed by their index like so `series[0]`. However in a Series, you can go further. Data in a Series can be accessed in the following ways

* Integer Index eg. `series[0]` or `series.iloc[0]`
* Associative access using an Index Array eg. `stock_returns["IBM"]` or `stock_returns.loc["IBM"]`
 * A Series can have an associated Index Array, and you can use values from this Index array to lookup values in the Series regardless of their actual location. Consider the following example

In [31]:
stock_returns = pd.Series([0.05, 0.10, 0.07, -0.10, 0.09], index=['IBM', 'GOOG', 'AMZN', 'GE', 'GM'])

# Numeric indexed access
print(stock_returns[0])
print(stock_returns.iloc[0])

# Associative index access
print(stock_returns["GOOG"])
print(stock_returns.loc['GOOG'])

0.05
0.05
0.1
0.1


#### Exercise

Given two data sets of countries and employment values, write a function that returns back the country with the maximum employment value and the name of that country

In [32]:
countries = [
    'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina',
    'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
    'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
    'Belize', 'Benin', 'Bhutan', 'Bolivia',
    'Bosnia and Herzegovina'
]

employment_values = [
    55.70000076, 51.40000153, 50.5, 75.69999695,
    58.40000153, 40.09999847, 61.5, 57.09999847,
    60.90000153, 66.59999847, 60.40000153, 68.09999847,
    66.90000153, 53.40000153, 48.59999847, 56.79999924,
    71.59999847, 58.40000153, 70.40000153, 41.20000076
]


def max_employment(emp_series):
    # Get the index that has the max value
    # Hint: Use the Series.argmax() function to get the index of the max value
    

    #answer below
    country = emp_series.argmax()
    return emp_series.loc[country], country)

# Employment data in 2007 for 20 countries
employment = pd.Series(employment_values, index=countries)
max_employment(employment)

SyntaxError: invalid syntax (<ipython-input-32-ed8bd8e05b5e>, line 25)

### Vector Operations

Pandas Series has good support for vector operations similar to Numpy Arrays, however the presence of index arrays in Series make these operations more powerful. Series uses these index arrays to match up corresponding elements by index (*rather than by position*) to make for more intuitive and convenient operations. 

Consider the following example:

In [33]:
math_scores = pd.Series([11, 22, 31, 41], index=['Amber', 'Billy', 'Charlie', 'David'])
science_scores = pd.Series([10, 20, 30, 40], index=['Billy', 'David', 'Amber', 'Charlie'])

print(math_scores + science_scores)

Amber      41
Billy      32
Charlie    71
David      61
dtype: int64


In [ ]:
# Addition when indexes are the same
if False:
    s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
    s2 = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
    print(s1 + s2)

# Indexes have same elements in a different order
if False:
    s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
    s2 = pd.Series([10, 20, 30, 40], index=['b', 'd', 'a', 'c'])
    print(s1 + s2)

# Indexes overlap, but do not have exactly the same elements
if False:
    s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
    s2 = pd.Series([10, 20, 30, 40], index=['c', 'd', 'e', 'f'])
    print(s1 + s2)

# Indexes do not overlap
if True:
    s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
    s2 = pd.Series([10, 20, 30, 40], index=['e', 'f', 'g', 'h'])
    print(s1 + s2)

For the case when indexes are not present in both Series, the result is `NaN`, which stands for `Not a Number`. Pandas offers several functions on the Series object to deal with these

```python
# Drop NaN elements
Series.dropna()

# Fill NaN elements with 0
Series.fillna(0)
```

In [ ]:
# Add two Series, fill missing index elements with 0 before addition
s1 = pd.Series([1, 2], index=['a', 'b'])
s2 = pd.Series([3, 4], index=['c', 'd'])
s1.add(s2, fill_value=0)

### Math operations

Like numpy, Series also has rich support for math operations that you can perform on its data.

You can also think of these operations as `reduce` operations, in that they reduce an entire Series vector down to `one` value.

In [ ]:
if True:
    print(math_scores.mean())
    print(math_scores.median())
    print(math_scores.std())

### Conditionals

Pandas Series supports a similar way of conditionally filtering its elements by indexing on a Boolean array as with numpy arrays. With Pandas Series you would provide the filtering condition within the [] which would then return back all of the elements in the Series for which the condition was `True`

In [ ]:
# Conditionals should be applied as vector operations, comparing the entire series in one go
if False:
    print(math_scores > 50)
    print(math_scores > math_scores.mean())
    
if True:
    print(math_scores[math_scores > math_scores.mean()])
    print(science_scores[science_scores > 30])

#### Exercise

For the Student Scores above, let's say we wanted to print out the students that were in the 90th percentile of the class (based on the sum of their math and science scores).

In [40]:
# Use the Series.quantile() function to determine the percentile cutoff and then use that value as a filter conditional


scores = math_scores + science_scores

print (scores[scores > scores.quantile(.9)])




Charlie    71
dtype: int64


### Series.apply()

Pandas Series offers the ability to run custom functions against its elements. This works by taking in a function as an argument and returning a new Series that holds the return values of the function `applied` to the elements of the original series. This is very similar to the python built-in `map()` function on Lists 

In [38]:
def square(x):
    return x**2

nums = pd.Series([1, 2, 3, 4, 5])

# "Applies" the function square to each element of nums and returns a new Series with the results.
nums.apply(square)

0     1
1     4
2     9
3    16
4    25
dtype: int64

#### Exercise

Given a Series of names, write a function that reverses these names and prints them out in the format `LastName, FirstName`.

In [42]:
names = pd.Series([
    'Andre Agassi',
    'Barry Bonds',
    'Christopher Columbus',
    'Daniel Defoe',
    'Emilio Estevez',
    'Fred Flintstone',
    'Greta Garbo',
    'Humbert Humbert',
    'Ivan Ilych',
    'James Joyce',
    'Keira Knightley',
    'Lois Lane',
    'Mike Myers',
    'Nick Nolte',
    'Ozzy Osbourne',
    'Pablo Picasso',
    'Quirinus Quirrell',
    'Rachael Ray',
    'Susan Sarandon',
    'Tina Turner',
    'Ugueth Urbina',
    'Vince Vaughn',
    'Woodrow Wilson',
    'Yoji Yamada',
    'Zinedine Zidane'
])

#the real answer
def reverse_names(names):
    def format_names(name):
        new_name = name.split()
        return '{}, {}'.format(new_name[1], new_name[0])
    return names.apply(format_names)
       
        
    
    '''
    Use the split() function on the stringsinsdie the  to separate the first and last names and then use
    String.format() to print it out in the desired format.
    
    Try to use the Pandas apply() function NOT a loop.
    '''
    
#     #my attempt #1
#     def 
#     return names.str.split('')
#     print names.string.format()
#     reverse_names.apply(names)
    
    
    
#     # reminder of how to format this
#     '{}, {}'.format(L,F)
    
    
    
    
    
reverse_names(names)

0             Agassi, Andre
1              Bonds, Barry
2     Columbus, Christopher
3             Defoe, Daniel
4           Estevez, Emilio
5          Flintstone, Fred
6              Garbo, Greta
7          Humbert, Humbert
8               Ilych, Ivan
9              Joyce, James
10         Knightley, Keira
11               Lane, Lois
12              Myers, Mike
13              Nolte, Nick
14           Osbourne, Ozzy
15           Picasso, Pablo
16       Quirrell, Quirinus
17             Ray, Rachael
18          Sarandon, Susan
19             Turner, Tina
20           Urbina, Ugueth
21            Vaughn, Vince
22          Wilson, Woodrow
23             Yamada, Yoji
24         Zidane, Zinedine
dtype: object

### Plotting

Pandas Series comes with inbuilt support for plotting data via the standard function `plot()`. Call `plot()` on its own to get a line-plot of the data in the Series using the default options. 

Pass options to plot to change the layout in the graph to [customize](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.plot.html#pandas.Series.plot) it. 

In [43]:
import seaborn as sns

employment = pd.Series(
    [75.8000030518, 75.8000030518, 75.5, 75.9000015259, 75.8000030518, 75.9000015259, 75.6999969482, 75.5999984741,
     75.5999984741, 75.5, 75.5, 75.5999984741, 75.5, 75.5, 75.5999984741, 75.5, 75.6999969482],
    index=[1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007]
)

employment.plot()
# employment.plot(kind='line', title="Employment")
#employment.plot.pie()

ModuleNotFoundError: No module named 'seaborn'

Consider the following exercise.

### Exercise
Given two data-sets, write a function that measures the direction of each of the element values with respect to their means.

The function should return two numbers.
 1. The number of times when an element in an array is above its mean and the element at the same index at the other data set is also above its mean. The same for when they are both below their means. This number records the number of times that the data set elements in the two arrays move in the same direction.
 2. The number of times when the elements of the data set move in opposite directions.So if an element in one array is above its mean and the corresponding element in the other array is below its mean or vice versa.

In [47]:
life_expectancy_values = [74.7, 75., 83.4, 57.6, 74.6, 75.4, 72.3, 81.5, 80.2,
                          70.3, 72.1, 76.4, 68.1, 75.2, 69.8, 79.4, 70.8, 62.7,
                          67.3, 70.6]

gdp_values = [1681.61390973, 2155.48523109, 21495.80508273, 562.98768478,
              13495.1274663, 9388.68852258, 1424.19056199, 24765.54890176,
              27036.48733192, 1945.63754911, 21721.61840978, 13373.21993972,
              483.97086804, 9783.98417323, 2253.46411147, 25034.66692293,
              3680.91642923, 366.04496652, 1175.92638695, 1132.21387981]

# Life expectancy and gdp data in 2007 for 20 countries
life_expectancy = pd.Series(life_expectancy_values)
gdp = pd.Series(gdp_values)


def variable_correlation(variable1, variable2):
    """
    Determine data set correlation
    
    Hint: Use the mean() function to determine the mean value in the data-set
    Use the logical operators to determine what values in each Series are above their means to get two series of 
    booleans. Then use the & operator to combine them into one Series of booleans that will give you the case for
    when both values are above their means. Do the same for the case when both values are below their means.
    Combine these two resultant series using the | operator to get a Series stating when the values in each index
    are either both above OR both below their means
    
    Use the value_count() function Series to return back the counts of Trues and Falses.
    """
    pass

    gdp_mean = gdp.mean()
    life_mean = life_expectancy.mean()

    return(((gdp > gdp_mean) & (life_expectancy > life_mean)) | ((gdp < gdp_mean) & (life_expectancy < life_mean))).value_counts()

variable_correlation(life_expectancy, gdp)

True     17
False     3
dtype: int64

We see in the output that in most cases the data-set elements are either both above or below their means, indicating that they are `positively correlated`. If we had a case where when one element went above its mean and the other corresponding element went below its mean that would indicated `negative correlation`, indicating the data-sets move opposite to each other.

### Resources

The pandas reference page provides copious documentation on the operations available on `Series`. To get more familiar with Series, be sure to check out the links here http://pandas.pydata.org/pandas-docs/stable/index.html. Information specifically about Series can be found here http://pandas.pydata.org/pandas-docs/stable/dsintro.html#series